export const LANDMARKS = {
  WRIST: 0,
  THUMB_TIP: 4,
  INDEX_TIP: 8,
  MIDDLE_TIP: 12,
  CENTROID: 9,
  RING_TIP: 16,
  PINKY_TIP: 20,
  MIDDLE_MCP: 10,
};

export const HAND_STATES = {
  NOT_DETECTED: "NOT_DETECTED",
  STARTING: "STARTING",
  WAITING: "WAITING",
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  HOLDING: "HOLDING",
  POINTING: "POINTING",
  SWIPE_NEXT: "SWIPE_NEXT",
  SWIPE_PREVIOUS: "SWIPE_PREVIOUS",
  SWIPE_UP: "SWIPE_UP",
  SWIPE_DOWN: "SWIPE_DOWN",
};

export type HandState = (typeof HAND_STATES)[keyof typeof HAND_STATES];
